### ISSUE TITLE
EIP-1014 failed to go through the workflow

### ISSUE THREAD

**Issue by fulldecent** [ethereum/EIPs#1698]
[EIP-1014](https://eips.ethereum.org/EIPS/eip-1014) is currently listed as draft status, however according to announcement from @Souptacular at https://blog.ethereum.org/2019/01/11/ethereum-constantinople-upgrade-announcement/ the latest EF version of clients will support this hard fork on block 7,080,000.

@vbuterin please use the EIP workflow process outlined in EIP-1.

**Comment by axic** [comment]
These are addressed in #1689 (and #1642 to be merged after the hardfork goes live).

**Comment by fulldecent** [comment]
Thank you for the reference. I request please that in future, project managers will promote to LAST CALL and then ACCEPTED status /before/ an EIP will be announced as part of a hard fork.

**Comment by bmann** [comment]
Can we close this issue?

**Comment by 5chdn** [comment]
Yes. In future, the cat herders eip monitoring subcommittee will assist here. 

https://github.com/ethereum-cat-herders/hard-fork-checklist/issues/4

**Comment by fulldecent** [comment]
Reference: this happened again on the latest hard fork https://github.com/ethereum/EIPs/pull/2447

This issue is still relevant
