### ISSUE TITLE
Reduce ETH issuance before proof-of-stake

### ISSUE THREAD

**Issue by lightuponlight** [ethereum/EIPs#186]
Coin vote is now underway on EIP-186:

http://carbonvote.com/

As an FYI, Carbonvote set this up on their own. I think they did a very nice job and thank them for serving the Ethereum community in this way.

Please, whatever your opinion is on EIP-186, let your voice be heard by participating in the coin vote!

--------------------------------------------------------------------------------------------
Modified EIP proposal with changes, followed by the original EIP proposal. These changes are based on feedback provided on Reddit and Github regarding this EIP regarding the issuance reduction schedule and minimum issuance level under proof-of-work.
--------------------------------------------------------------------------------------------

<pre>  
  EIP: 186
  Title: Reduce ETH issuance before proof-of-stake
  Author: Matthew Light | lightuponlight9@gmail.com
  Discussions-To: lightuponlight9@gmail.com
  Status: Draft
  Type: Standards Track
  Created: 2016-12-21
  Replaces:  N/A
  Superseded-By: N/A
  Resolution: N/A
</pre>

**Abstract**
A reduction in the issuance of Ether (ETH) is very likely to be price-supportive and lead to increasing investments in the platform and to help ward off speculative attacks on the value of Ether by promoters of competing platforms who offer, or plan to offer, reduced token inflation rates. This proposal is based on [a discussion on Reddit](https://www.reddit.com/r/ethereum/comments/5izcf5/lets_talk_about_the_projected_coin_supply_over/?st=iwzg8ikv&sh=34454d8e) about ETH token issuance rates that many people participated in, including Ethereum Foundation member Vitalik Buterin.

In the current version of Ethereum as deployed on the network, there is already a coded schedule of reduced issuance per time period due to the "ice age" (an increase in difficulty designed to incent the adoption of hard forks). Normally, the "ice ages" in Ethereum are postponed by hard forks and the issuance is kept at 5 ETH per block. This EIP suggests that instead, the reduction in issuance from the "ice age" be implemented in a stepwise fashion within the protocol rules on a set block number schedule and with a defined lower bound (such as the "tail emission" in Monero). The proposed block reward reduction timetable has been pushed farther into the future, and the terminal issuance level has been increased in light of discussions on Reddit and  github regarding this EIP.

**Motivation**
There is widespread interest within in the Ethereum community to reduce the current rate of ETH issuance. Uncertainty about the future total ETH token supply is a significant factor in reducing the market value of ETH which has negative externalities on the Ethereum ecosystem, by reducing the capital available by current investors to make investments in new Ethereum-based projects and by reducing the Ethereum Foundation's funds available for spending on salaries. Reducing ETH issuance in advance of proof-of-stake would provide a measure of reassurance to investors that their holdings of ETH will be diluted to a much lower degree. It would be helpful in the cryptoplatform marketplace for Ethereum to reduce issuance given that various competing platforms have or are planning lower issuance levels, such as Ethereum Classic. 
Additionally, reducing block rewards in the near future helps reduce a sense of pressure on the Ethereum network architects and developers to rush a proof-of-stake implementation and try to deliver it more quickly than would be prudent.
The terminal reward value of 2 ETH / block was chosen to reduce token supply inflation to around 4% annually, gradually reducing over time until proof-of-stake is launched. This is in line with the current Bitcoin token inflation rate of approximately 4%. In comparison, current proof-of-work ETH token inflation rate is a bit less than 13% per year.
A reduction of token emission under proof-of-work could lead to a reduction in network security. However, a plausible improvement in the exchange rate of ETH because of a reduction in issuance will lead to an increase in network security. It is unclear how much the ETH token price might increase due to a lowered issuance rate, but the positive response of Bitcoin price to issuance reductions ("halvening") is encouraging.

**Specification**
The current issuance level for ETH is 5 ETH per block, with various kinds of uncle rewards also provided. This EIP proposes that no change to the relationship between block rewards and uncle rewards be made, but instead that all uncle and uncle inclusion rewards be downsized proportionally with the provided block reward schedule.
The proposed reduction in issuance is an approximation for providing stepwise issuance reduction approximately matching the "ice age" coin issuance reduction already built into the current specification of the Ethereum software. Vitalik Buterin gave an estimate of this reduction on Reddit:
https://www.reddit.com/r/ethereum/comments/5izcf5/lets_talk_about_the_projected_coin_supply_over/dbc66rd/
Based on the ice age blocktime lengthening data Vitalik provided, the following reduction of block reward schedule is proposed as a reduction in issuance that is smaller than the reduction already scheduled (via longer blocktimes caused by the "ice age" PoW difficulty bomb). The reduction schedule is also significantly delayed over the "ice age" reduction already contained in the code:
Block 3700000 - Block reward reduced to 4 ETH / block
Block 5000000 - Block reward reduced to 3 ETH / block
Block 7000000 - Block reward reduced to 2 ETH / block (minimum block reward until proof-of-stake)
As previously stated, all uncle rewards should be proportionally reduced along with the main block reward.
The reduction in issuance specified in this EIP should also be accompanied with a change to push back the "ice age" date into the future as best determined by the Ethereum Foundation in the context of planning for the Casper / proof-of-stake release.
In the light of discussions with members of the Ethereum community and the Ethereum Foundation, this EIP recommends a coin vote should be taken to determine the level of community support before a decision about whether to implement it.

**Rationale**
This design is deliberately simplified from the issuance function Vitalik used to calculate his predicted blocktime schedule with relatively few block reward amount transition changes in order to minimize implimentation difficulty across the various Ethereum clients. No change in the relationship between block and uncle rewards is made to avoid introducing unforseen game-theoretic changes in mining strategy. Minimum planned proof-of-work issuance is set to 2 ETH / block to provide a baseline level of security rewards for proof-of-work close to Bitcoin's current issuance rate until the transition to proof-of-stake.

**Implementation**
This EIP must be implemented in all Ethereum validating nodes by a hard fork, either in a currently-planned hard fork such as Metropolis, or in a separate hard fork.

--------------------------------------------------------------------------------------------
Original EIP proposal below
--------------------------------------------------------------------------------------------

<pre>  
  EIP: 186
  Title: Reduce ETH issuance before proof-of-stake
  Author: Matthew Light | lightuponlight9@gmail.com
  Discussions-To: lightuponlight9@gmail.com
  Status: Draft
  Type: Standards Track
  Created: 2016-12-21
  Replaces:  N/A
  Superseded-By: N/A
  Resolution: N/A
</pre>

**Abstract**
A reduction in the issuance of Ether (ETH) is very likely to be price-supportive and lead to increasing investments in the platform and to help ward off speculative attacks on the value of Ether by promoters of competing platforms who offer, or plan to offer, reduced token inflation rates. This proposal is based on [a discussion on Reddit](https://www.reddit.com/r/ethereum/comments/5izcf5/lets_talk_about_the_projected_coin_supply_over/?st=iwzg8ikv&sh=34454d8e) about ETH token issuance rates that many people participated in, including Ethereum Foundation member Vitalik Buterin.

In the current version of Ethereum as deployed on the network, there is already a coded schedule of reduced issuance per time period due to the "ice age" (an increase in difficulty designed to incent the adoption of hard forks). Normally, the "ice ages" in Ethereum are postponed by hard forks and the issuance is kept at 5 ETH per block. This EIP suggests that instead, the reduction in issuance from the "ice age" be implemented in a stepwise fashion within the protocol rules on a set block number schedule and with a defined lower bound (such as the "tail emission" in Monero). The proposed block reward reduction timetables and the issuance floor are open to alternative suggestions by the Ethereum community if desired.

**Motivation**
There is widespread interest within in the Ethereum community to reduce the current rate of ETH issuance. Uncertainty about the future total ETH token supply is a significant factor in reducing the market value of ETH which has negative externalities on the Ethereum ecosystem, by reducing the capital available by current investors to make investments in new Ethereum-based projects and by reducing the Ethereum Foundation's funds available for spending on salaries. Reducing ETH issuance in advance of proof-of-stake would provide a measure of reassurance to investors that their holdings of ETH will be diluted to a much lower degree. It would be helpful in the cryptoplatform marketplace for Ethereum to reduce issuance given that various competing platforms have or are planning lower issuance levels, such as Ethereum Classic. If a large amount of opposition to this EIP for issuance reduction is seen in the community, this EIP could be submitted for a coin vote.
Additionally, reducing block rewards in the near future helps reduce a sense of pressure on the Ethereum network architects and developers to rush a proof-of-stake implementation and try to deliver it more quickly than would be prudent.
The terminal reward value of 1.5 ETH / block was chosen to reduce token supply inflation to around 3% annually, gradually reducing over time until proof-of-stake is launched. This is in line with but slightly less than current Bitcoin token inflation rate of approximately 4%. In comparison, current proof-of-work ETH token inflation rate is a bit less than 13% per year.
A reduction of token emission under proof-of-work could lead to a reduction in network security. However, a plausible improvement in the exchange rate of ETH because of a reduction in issuance will lead to an increase in network security. It is unclear how much the ETH token price might increase due to a lowered issuance rate, but the positive response of Bitcoin price to issuance reductions ("halvening") is encouraging.

**Specification**
The current issuance level for ETH is 5 ETH per block, with various kinds of uncle rewards also provided. This EIP proposes that no change to the relationship between block rewards and uncle rewards be made, but instead that all uncle and uncle inclusion rewards be downsized proportionally with the provided block reward schedule.
The proposed reduction in issuance is an approximation for providing stepwise issuance reduction approximately matching the "ice age" coin issuance reduction already built into the current specification of the Ethereum software. Vitalik Buterin gave an estimate of this reduction on Reddit:
https://www.reddit.com/r/ethereum/comments/5izcf5/lets_talk_about_the_projected_coin_supply_over/dbc66rd/
Based on the ice age blocktime lengthening data Vitalik provided, the following reduction of block reward schedule is proposed as a very rough approximation of the existing specification's reduction in issuance (via longer blocktimes caused by the "ice age" PoW difficulty bomb):
Block 3700000 - Block reward reduced to 4 ETH / block
Block 3900000 - Block reward reduced to 3 ETH / block
Block 4100000 - Block reward reduced to 2 ETH / block
Block 4150000 - Block reward reduced to 1.5 ETH / block (minimum block reward until proof-of-stake)
As previously stated, all uncle rewards should be proportionally reduced along with the main block reward.
The reduction in issuance specified in this EIP should also be accompanied with a change to push back the "ice age" date.

**Rationale**

This design is deliberately simplified from the issuance function Vitalik used to calculate his predicted blocktime schedule with relatively few block reward amount transition changes in order to minimize implimentation difficulty across the various Ethereum clients. No change in the relationship between block and uncle rewards is made to avoid introducing unforseen game-theoretic changes in mining strategy. Minimum issuance is set to 1.5 ETH / block to provide a baseline level of security rewards for proof-of-work close to but slightly below Bitcoin's current issuance rate until the transition to proof-of-stake.

**Implementation**
This EIP must be implemented in all Ethereum validating nodes by a hard fork, either in a currently-planned hard fork such as Metropolis, or in a separate hard fork.

**Comment by realcodywburns** [comment]
Delaying the bomb isn't a problem, it is currently included in parity, nor is changing issuance rules. As for a coin vote, Vitalik bomb 2.0 proposal from a few months back offered a mechanism to choose a path and kill the other fork that may be useful.

**Comment by surg0r** [comment]
I would support this proposal. 

Ethereum is an amazing project with aims far greater than the simple monetary goals of bitcoin. But it is the digital scarcity of cryptocurrency that gives value of the underlying tokens for each chain. Do not forget that ethereum already has 87M ether in existence with another 13M expected in the coming years. For ethereum to work as a cryptocurrency then ether must have value - or PoS will not work and the numerous startups with ICO's held in ether risk failure. 

Perception is everything and general perception is that ethereum has a loose inflationary monetary design. This isn't accurate because of course bitcoin will continue to inflate for a long time. But bitcoin has a perceived hard cap and everyone knows the mantra that 'there will only ever be 21 million bitcoins'. Ethereum has no hard emission schedule published for post-PoS or an upper limit / upper bound to inflation decided. This is surprising for the second biggest cryptocurrency asset in the space in terms of market capitalisation. Developers openly saying that ethereum is not a store of value is also extremely unhelpful in my personal opinion when trying to grow an ecosystem based at it's root upon programmable digital money.

Lowering coin emission and monetary inflation to anything below 2% in the short term would improve things dramatically. Further implementing a hard cap at 100M with exponentially falling rewards until then (say over 100 years) would also be positive, especially in the context of ethereum post-POW. Even if this did not alter the actual emission schedule much - appearances are everything.

**Comment by jibuji** [comment]
I agree that the reduction of issuance should be done in the near future. But, I think the issuance mechanism should be simple. The simplicity will not only reduce the risk of bug, but also make the mining reward easy to calculate. 

In this EIP, there are two reduction mechanism: one is the `ice age`, which is to lengthen the blocktime and has been  coded in current Ethereum version;  the other one is to reduce the rewards per block. Both of these two mechanism are great, but I prefer to choose only one of them. 

As to reduce the inflation to 3%, I prefer to change the parameters, instead of combining these two mechanism.

**Comment by Nipol** [comment]
If you look at it, it seems that compensation for "Stale Block" has not been considered. Is this part of the discussion being discussed?

**Comment by aakilfernandes** [comment]
I haven't gone into the technicals, but I agree with the spirit of this proposal. However I'd like to see the block subsidies based an on-chain oracle, or some other system where contracts can read them. Maybe a simple BLOCK_SUBSIDY op code would suffice.

**Comment by larspensjo** [comment]
Some arguments against this request (but a delay in the Ice Age is probably going to be needed).

1. It is supposed to help investors. Although a play of words, but I see investing into the ether value as a speculation. With investment into Ethereum, I see investment into tools, contracts and other related services. This type of investment does not benefit from an increased value of ether.

1. Changing the consensus rules to encourage a higher ether price is not going to be seen kindly upon from outside of the Ethereum community. There is a risk that it will be interpreted as profits going first. The issuance rate is one of the fundamentals people look at when analyzing a cryptocurrency. It should not be changed lightly. One reason for the proposed change is uncertainty of the future issuance. I believe the proposed change may increase this uncertainty, not decrease it.

1. The Ethereum Foundation is one of the bigger holders of ether, and would benefit the most from an increased value. Also, some of the members of EF hold large amounts of ether. Again, very questionable. What would be the next step, a hardfork that mints 1 million new ether dedicated to the EF? ETH's price is something completely external to the development of the Ethereum protocol.

1. There is a risk hash rate will fall proportionally. Do we really want that?

1. Until POS, this change of reward is a temporary change. Suppose we are talking about one extra year, running with  lower rewards instead of the current 5 ether/block. With POS, we  will get the lower reward system anyway, so it is only one year of difference.

1. A discussion around this subject is prone to self confirmation. If you own ether, you may be influenced positively by the idea.

1. POW need higher rewards than POS because it has higher operational costs.

1. Any reference to another cryptocurrency is irrelevant for this discussion. That is, a change based on competition to other currencies is not a good change. The decision to adopt this EIP should be exactly the same as if Ethereum was the only existing cryptocurrency.

1. There is a risk that the hard fork will not be accepted 100%, leading to another split of the community. This could be very damaging.

**Comment by dip239** [comment]
> There is a risk that the hard fork will not be accepted 100%, leading to another split of the community. 

Exactly my thoughts! It is very dangerous!
This EIP implies that 99,9% of all miners will follow the fork decision. This implication is wrong.

Any attempt to take away somebody's money (here the miner's) for common weal is not quite fair and very risky. Even democratic ballots is not the suitable governance model for miner's community, because the minority have strong and continuous chain of incentives to rebel and split off the coin.

So, don't relay on decision. Let us relay on incentives:
Ethereum could make an offer to miners to convert theirs freshly mined ethers into Casper mining deposit.  I would also give an extra stake voting power to those stake.

Pros:
- Inflated Ethers become sterilized as Casper deposit.
- PoW miners become fair transition path to PoS
- Ethereum/PoS becomes better distribution of stakeholder (not only the oligopoly of ETH whales)

Contras:
?

**Comment by Nogreedy** [comment]
reduce inflation now
reduce fast
reduce strong
I "vote" for Original EIP 186 proposal.
Inflation now (1Million ETH/month) is totally insane

**Comment by mjdillon** [comment]
Can you cite any sources to support your assertion that
> Uncertainty about the future total ETH token supply is a significant factor in reducing the market value of ETH

**Comment by rcawston** [comment]
I suspect nearly the entire mining community is likely to be against this.  Do we really want to alienate the group that maintains and secures the network when casper PoS is still a glimmer off in the future?  I say no - instead, remove the ice age, leave block subsidy static, and get PoS ready.

**Comment by matttrichards** [comment]
@mjdillon I am not investing nearly as much as I otherwise would simply because I am not yet confident in the economics of ethereum as many parameters have yet to be defined (final token supply being one of them). I imagine I am not alone in this hesitancy - hence the effect on market cap.

**Comment by alex-miller-0** [comment]
I would like to see more discussion on this EIP.

The argument that miners will reject this out of self interest is weak IMO. Mining follows profitability. If we assume constant demand, the price will increase at a rate proportional to the decrease in issuance and in my estimation there is a very high probability of demand increasing significantly.

The price is extremely important for attracting developers to the ecosystem and, more importantly, incentivizing them to provide value. An increase in price pays for the time of developers who could otherwise be providing value elsewhere.

I don't think the ecosystem *needs* this, but frankly I don't understand the resistance. This one's a no brainer to me because we're not going to see PoS this year. Package it into metropolis.

**Comment by simondlr** [comment]
> I don't think the ecosystem needs this, but frankly I don't understand the resistance.

@larspensjo & @AlexeyAkhunov gives good reasons.

The main resistance is the uncertainty around the drop in hashrate security for short-term, short-sighted price gains.

> Mining follows profitability

Why stop at 1.5 ETH/block? How do we know that a specific hashrate is *good enough*? Do we calculate a dollar amount to buy hardware to 51% and collectively decide at a nr? $100m? $50? $25m? How do we know what's a good nr? You can't assume constant demand either.

Don't change something that's not broken, especially if it's just a short-term thing (max 2 years, if not sooner).

There's way too many uncertainties with manipulating this. Split community, uncertainty about price events, magic numbers.

**Comment by surg0r** [comment]
Sounds like you are a miner..

**Comment by simondlr** [comment]
> Sounds like you are a miner..

Been in the crypto space since 2011. Never mined a single block. ;)

**Comment by surg0r** [comment]
Well asking how much hash power is enough is slightly silly because:

a) POS makes it all irrelevant.
b) hash power loosely follows price - but price is linked to supply and
demand. Presumably falling supply will be price positive. But even if not
so then
c) 51% attack is theoretical and the network is massively harder to attack
now than a year ago. Even if hash power drops significantly it remains a
non-event.
d) issuance has never predicted hash power..Nor IMO should you try and
predict hash power with issuance schedules (see bitcoin)..

In summary it's complex but reducing issuance is likely to be price
positive for existing tokens which will be beneficial for all but a cohort
of miners who are being phased out of block selection in any case.

Regards,

Peter

**Comment by simondlr** [comment]
> Presumably falling supply will be price positive

Not a given. Falling supply could lead to falling security, leading to distrust in the platform, leading to falling price. Not saying this will happen, but it could. It's not a trivial possibility at least.

> 51% attack is theoretical

Well it is a legitimate concern. Low cap altcoins have been 51% attacked. It's unlikely to happen in ETH. But then, I come back to my original question. If short-term price-gain is wanted, why stop at 1.5 ETH/block? There's no good reason just besides saying: "There should be *some* security, but at least we should be around Bitcoin's current issuance rate." It's not satisfactory reasoning. 

> issuance has never predicted hash power

This is true. Price has been the main factor. But zero issuance in PoW means a dead chain (tx fees won't save you here). Issuance *is* correlated to hash power.

> beneficial for all

This I don't agree with. I'm legitimately concerned with the negative impact of perception of changing monetary policy to fit short-term greed (more "immutability" trolls coming out of the woodworks), and legitimately concerned about unknown events regarding security and the changing of expectations (splitting the community).

> In summary it's complex

This is true. Thus, current proposals need substantially more economic/theoretical backing to prove that we won't steer into a disaster.

It's not a straight-forward decision.

**Comment by surg0r** [comment]
>Falling supply could lead to falling security, leading to distrust in the
platform, leading to falling price. Not saying this will happen, but it
could. It's not a trivial possibility at least.

This is a trivial edge case IMO. Which is so unlikely as to be discounted
entirely. Issuance isnt proposed to reduce to zero in any case. Did people
call for the same in bitcoin in the last two Halvings (far more severe
curtailing of supply)? If you are around since 2011 then you know the truly
resounding answer.

For me cryptocurrency is supposed to be better than fiat. We don't have to
listen to bankers justifying inflation anymore. Excessive issuance is
unnecessary inflation. Why not argue that we need more issuance to entice
in more hash power? Because issuance doesn't predict hash power, and hash
power doesn't predict price but instead follows it.

At the heart of ethereum, for all it's lofty goals, is the basic premise it
is digital scarce cash which may not be counterfeit. I'll support the
project in any case but let's keep it realistic!

Regards,

Peter

**Comment by alex-miller-0** [comment]
> How do we know that a specific hashrate is good enough

As I mentioned above, I don't believe hashrate will be significantly affected by this, assuming price tracks decreasing issuance. I think Bitcoin halvening events are good indicators to follow.

> Don't change something that's not broken, especially if it's just a short-term thing (max 2 years, if not sooner).

In my opinion, nothing about this is "short-term". Ethereum itself is only a year and a half old, so I think it's a mistake to assume it's at a stable state.

> uncertainty about price events

Everything is uncertain in this space. Not sure what you mean by this.

> magic numbers

Is the current issuance not a magic number? What about the re-priced op codes? Everything is an approximation of some truth.

> Split community

Okay this one I'm with you on. Agreed that we should abort if there are people in *this* community that are willing to leave over it. That's why I wanted to get more discussion on this. I personally don't care what r/Bitcoin or CoinTelegraph have to say about it, but I agree that it's not worth splitting the community over. I just don't think that's the case.

**Comment by simondlr** [comment]
> Why not argue that we need more issuance to entice in more hash power?

Good point. No one knows what's the effective trade-off to retain the highest security. We might be underperforming. Zero issuance = dead chain. %4m inflation per block is also a dead chain. Somewhere along this line you get the most security. What *is* that?

> I don't believe hashrate will be significantly affected by this, assuming price tracks decreasing issuance

... but there's my problem. How do *know* that?

> I think Bitcoin halvening events are good indicators to follow.

And how do we know that Bitcoin would not have had a much higher security if it kept a constant subsidy?

These are still conjectures.

> In my opinion, nothing about this is "short-term"

Changing something like this whilst Ethereum is going to be around for decades *is* short-term price greed.

> Is the current issuance not a magic number?

It is (I might be wrong and Vitalik and co based the percentage inflation on actual economic research). So it works fine for now. It might not have been the best magic number, but don't change to other magic numbers when it's not broken.

---

Basically, all I'm saying is. There's no need to fiddle with monetary policy in the short-term. If we are, we need a lot more substantial research for why fiddling with it is a good idea. And not just conjectures. Stay with the working status quo, unless there's substantial convincing evidence otherwise.

Others might require less convincing evidence, or the trade-offs are substantially more obvious to others. It's just so nebulous to me, that it feels like tinkering a car engine whilst driving and not looking at the road ahead.

**Comment by alex-miller-0** [comment]
> These are still conjectures.

Fair enough. I totally understand the not-broke-don't-fix argument and perhaps it does apply. I personally think our flat issuance has hindered growth and will continue to do so, but maybe I'm wrong.

I'll back off and leave it to others to comment.

**Comment by Nogreedy** [comment]
@alex-miller-0 : I agree with you : At this time, ETH issuance system is not adapted...  
We have to observe what others cryptos are doing... 

![Uploading annual-inflation-rate_Litecoin-bitcoin-dash-monero-dogecoin_inflation.png…]()

**Comment by Aza1** [comment]
Fully support this proposal en route to PoS.

**Comment by lightuponlight** [comment]
Coin vote is now underway on EIP-186:

http://carbonvote.com/

As an FYI, Carbonvote set this up on their own. I think they did a very nice job and thank them for serving the Ethereum community in this way.

Please, whatever your opinion is on EIP-186, let your voice be heard by participating in the coin vote!

**Comment by pedrosoftz** [comment]
any news about coin reduction from Last Core Devs Meeting 13 ?

**Comment by 5chdn** [comment]
FYI

> Block 3700000 - Block reward reduced to 4 ETH / block

This block already passed :)

**Comment by alex-miller-0** [comment]
Are you sure?

https://etherscan.io/block/3809183

Still showing 5 ETH base reward.

**Comment by 5chdn** [comment]
> Are you sure?

Yes, I'm sure: 3800000 > 3700000. 

This proposal is not picked up yet, I just said that the initial proposed block 3700000 already passed and the proposal might need some readjustments. Let me push ahead:

- Block 5000000 - Block reward reduced to 4 ETH / block
- Block 6000000 - Block reward reduced to 3 ETH / block
- Block 7000000 - Block reward reduced to 2 ETH / block (minimum block reward until proof-of-stake)

Where Block 5M is December 2017, 6M May 2018, and 7M November 2018. 

And to get an idea: 4M is already next month. 8M is April 2019, so going down in steps like 5000000-6000000-7000000 is the most realistic schedule we currently could come up.

**Comment by alex-miller-0** [comment]
Oh sorry I thought you meant the proposal was picked up and was in motion. Yes I agree, the numbers should be updated, but I think the principle is just a lower issuance rate effective until PoS.

Just read the [meeting notes](https://github.com/ethereum/pm/blob/master/All%20Core%20Devs%20Meetings/Meeting%2014.md) and it sounds like this EIP was rejected. I would like to add that although I agree a 2-3M difference is not worth a controversial hard fork, this assumes that PoS will be delivered on time. I know the core devs have a much better idea of when that will be, but I want to make the point that this different doubles on the order of every 6 months.

**Comment by niklasbuschmann** [comment]
Something to keep in mind: Most high-end AMD GPUs are [sold out](http://www.pcgamer.com/blame-cryptocurrency-miners-for-scarcity-of-radeon-rx-580-and-570-cards/) because of the high block rewards.

A lot of the wealth from people who buy ETH at high prices is redistributed to GPU manufacturers and electricity companies.

**Comment by alex-miller-0** [comment]
As the network suffers under a massive backlog of transactions while miners remain too lazy to increase the block size, I would like to submit another argument for this EIP. 

The block reward is clearly too high with respect to transaction fees. This is evidenced by dwarfpool and f2pool continuing to mine empty blocks because **it is profitable to do so**.

These are my arguments for this EIP, which I continue to support and would still very much like to see included in Metropolis:

1. The block reward is too high with respect to transaction fees and it is causing congestion in the network **today**.
2. Proof-of-Stake has no expected release date and argument 1 will continue to be a problem for the foreseeable future.
3. Mining is absurdly profitable. Far more profitable than it needs to be. Ethereum could see a considerable decrease in issuance and still be extremely profitable to mine.
4. Inflation is uncapped and still applies sell pressure to the market price. My original argument (that developers are incentivized by a rising price) is moot today (since the price has risen considerably) but is still qualitatively true and fundamentally nothing has changed except for newfound speculation.

**Comment by alex-miller-0** [comment]
Per Core Devs Meeting 19 notes, I suggest these numbers be updated.

I suggest a linear decrease:

    Reward = 5 - 0.002*(Bi-B0)

Where `B0` is the metropolis block and `Bi` is the current block.

This would lead to the following issuances (excluding uncles):

- 4.98 ETH at `B0 + 10,000`
- 4.8 ETH at `B0 + 100,000`
- 3 ETH at `B0 + 1,000,000`
- 1 ETH at `B0 + 2,000,000`

It hits 0 ETH at `B0 + 2,500,000`, which (assuming 15 second blocks) would take 434 days.

**Comment by Nogreedy** [comment]
I propose simplicity, efficiency and logical no-controversy action : 
The issuance rate should be kept at the level it would be at if the difficulty bomb were to stay.

**Comment by simondlr** [comment]
@alex-miller-0 anything that moves to zero seems risky on a schedule unrelated to the PoS milestones. Initial estimates were that Casper was going to be implemented and online 6 months ago (hence us battling with the difficulty bomb atm). If issuance were to decrease, I would rather err on attaching it to PoS milestones rather arbitrary block limits? Or maybe both in some way?

**Comment by alex-miller-0** [comment]
> I propose simplicity, efficiency and logical no-controversy action :
The issuance rate should be kept at the level it would be at if the difficulty bomb were to stay.

The problem is that it would decrease exponentially. I worry it would hit zero before Casper was released.

>  anything that moves to zero seems risky on a schedule unrelated to the PoS milestones

I agree, although 434 days feels pretty safe given my perception of Casper's release schedule. The function could certainly be made more efficient, though I'm not aware of any concrete deadlines on the various stages of Casper. Perhaps a breakdown of deadlines and expected block reward reductions would help here as we go from PoW to various stages of PoW/PoS to full PoS @vbuterin

> We have some gut feeling that we are spending too much on security, but how does that extrapolate to an effective decision based on numbers? Is it possible?

Good question. I would guess it is not possible. We would need to fill the space of "Num. consensus failures as a function of hash power as a function of block reward", which would require us to have consensus failures, which we don't want. Your earlier points about the numbers being uncertain are true - we are definitely taking stabs in the dark. I have always felt strongly that we were far away from consensus failure (even at $10), though I don't have the numbers to prove it.

I guess the argument the devs seem to favor is that Casper issuance will drop precipitously and discontinuities (e.g. 5 -> 0) are inefficient by nature.

**Comment by lightuponlight** [comment]
The developers had a good discussion on EIP-186 during their latest all core devs meeting . It sounds like there is growing support for some kind of reduction in issuance prior to proof-of-stake. I believe this is a good idea for a number of reasons:

1) Block reward for Ethereum mining is extremely high, far larger than the current block reward for Bitcoin or any other cryptocurrency (likely for all other cryptocurrencies combined).

2) A reduction in block reward will incent more miners to include more transactions as it increases the percentage of block reward coming from transaction fees, improving network throughput capacity.

3) We are likely to be 100% on proof-of-work for the next year, as Casper has been delayed and needs to be done very carefully and with sufficient time to plan / test / release.

4) The Ethereum network is currently using more electricity to generate hashes than many entire countries, so overpaying for network security is very wasteful.

If the developers are open to moving forward on it, I think a revised emission schedule should be decided on as soon as feasible so this can be implemented and tested in a timely manner and included in Metropolis.

Carbonvote appears to be not working correctly right now, but the last time I looked the reduction favored by the mean coin vote seemed to be to around 3 ETH / block. Overall support for reduction on Carbonvote was overwhelming, over 99% every time I checked.

By the time of Metropolis going live I expect block time will be sufficiently long that a change to 3 ETH / block and a 14 second block time should be roughly in line with 5 ETH / block and an expected block time close to 24 seconds for the current Homestead chain at that date.

A simple one-time reduction to a fixed value such as 3 ETH / block (and proportional uncle reductions) is going to be easiest block reward reduction for the various Ethereum client node developers to implement and test.

Here are some of the comments from the various core developers, pasted from github:

Vitalik: "I want to re-bring up EIP 186; I think we are more than secure enough with ETH at these levels (or even at $50) and wasting more electricity than some countries is tragic so we could use a decrease"

Avsa: "The plan for Casper is to start with a slow transition from PoW, right? Is the idea to have a slowly decreasing reward? Maybe if we set a slowly decreasing schedule now - which then has a slight uptick when PoS comes around, it might be an actual incentive for miners to move to the PoS chain when that is ready"

"I am also tentatively in favor of it with we can justify it in terms of incentiziation. I am against it if it’s heavily dependent on ether price or if it’s about pure economic planning Maybe what is needed for this conversation to move forward is a clear proposal with numbers backing it up: reduce to X on Y date then changes to N when PoS comes etc. We also need to account for black swans: what if the new ice age comes, Casper isn't ready and ether is under $20?"

Nick: "My own opinion on this has evolved; I'm tentatively in favor of at least a modest reduction. Exactly because it's a step towards the reduced issuance Casper is likely to have."

**Comment by lightuponlight** [comment]
There have been a lot of suggestions about complicated issuance reductions, as well as a lot of suggestions that issuance should reduce along the issuance path of the ice age.

I see two serious problems with those suggestions.

1) Complicated issuance reductions are much more likely to result in bugs and even in consensus failures.

2) Reducing issuance too low can compromise hash rate and encourage attempts at 51% attacks.

The easiest and most straightforward issuance reduction is a one-time reduction at the time of the hard fork. Given that we will probably be seeing blocktimes in the 25-30 second area by the time Metropolis goes live, a reduction from 5 to 3 (at the same time as blocktime is reset to 14-15 seconds) is not likely to reducing mining profits at all while at the same time will fix the slowing block time.

The carbonvote (when it was working) seemed to indicate a Schelling point for reduction to around 3 ETH / block as well.

**Comment by alex-miller-0** [comment]
@lightuponlight 

My issue with a new flat rate is that once Metropolis is released, all leverage against miners is gone. The current alternative is to mine a chain that will grind to a halt, so I think miners will accept just about any reduction in issuance if it means they can continue to mine a profitable chain, even if only for another year.

I'm also worried that a flat 3 ETH reward may still be too high. 

Why do you think a linear decrease lead to consensus failures/bugs?

**Comment by kybarnet** [comment]
> a reduction from 5 to 3 (at the same time as blocktime is reset to 14-15 seconds) is not likely to reducing mining profits at all while at the same time will fix the slowing block time.

This is absolutely terrible. Terrible. The Tax of Accumulated Wealth of Ethereum should never be fixed, or increasing. It must perpetually remain below that of market demand, and thus must decrease once it reaches equilibrium. I feel terrible that none have been discussing or understanding this.

This is quite simple to prove mathematically, under all circumstances. It is a factually, undeniable statement, regarding asset security.

What is the Tax, or Hash Security, cost for Ethereum, for the day of July 26, 2017?

Hash Security costs linearly increases with price, thus you first must discover the fair price for Ethereum.

Assuming you are less intelligent than the combining financial markets, we accept the Buy and Sell values of Ethereum as the Fair Value, or perhaps $190. However, feel free to make this any other number you want.

On that day, what is the Cost to run Hash Security, relative to payout?

One would speculate the cost to run Hash Security would approach payouts, or a rate of 100%, however, some suggest it is closer to 80% or even 10%. It makes no difference which number you choose, the result is always the same. However, you we can call this the 'minimum rate of miner burn required to sustain current levels of operation' (though it is completely irrelevant, some believe it not so).

So for our example we have:

Fair Value = $190

Minimum Miner Burn Rate = 100%

Next, we can assess the rate of expenses paid to the miners, which equates to (standardized to 15 Sec block times, and 94 Mil blocks):

5,760 Blocks x 5 ETH = 28,800 ETH - 28,800 ETH x $190 x (Minimum Miner Burn Rate) = $5,472,000

In order to go 1 single day, without losing value, Ethereum must Market $5,472,000 of Ethereum to New Investors, to sustain the current price point of $190. Which is to say, that if there are not enough Buyers at the price of $190 over the course of a day to purchase $5,472,000 worth of Ethereum, then they must begin to sell at $189, $188, $187, and so on, until they are able to pay for the their day to day expenses in $ or Yen or Marks, through the sell of Ether bonuses.

Miners also earn $24 Million to $48 Million in Transaction Fees (ETH, BTC), which are negotiated at fair values in today's dollars. The bonuses are always in addition to these fees. Together, the Fees and Bonuses, make up Block Reward.

Regardless, if Demand was to exceed that of $5,472,000 then the price of Ethereum would necessarily go up, to $191, $192, $193, and so on, until there were enough veterans or New Expenses created to meet Demand.

Thus, assuming we are less intelligent than the collection of all Market Forces, we know the Daily Demand and the Daily Expenses to be equal to one another, or $5,472,000 at the price of $190, with 100% burned daily.

If the Expenses were to be reduced, from that of $5,472,000 to that of $1,094,400 Daily, and Demand remained constant, than what would happen to the price of Ether?

Over time, it would achieve Equilibrium at : $190 / ($1,094,400 / $5,472,000) = $950 Per ETH, which is to say Daily Demand ($5,472,000) equals that of Daily Expenses ( 5,760 Blocks x 1 ETH = 5,760 ETH x $950 = $5,472,000. Any day in which Demand is more than that of Expenses, the price must necessarily rise to $191, $192, $193, and so on, or until enough Veterans are willing to cash out.

Put another way, if Hash Security Exp was reduced to $1 Million daily July 27th, then $4,377,600 Veterans must liquidate their holdings every single day to keep the price at $190, forever. Otherwise, it must go up. It must continue until there are no Veterans left, or Daily Expenses equal Daily Demand, which would occur at $950.

This is without any change of Demand.

At $950 the $ of Expenses at 1 ETH per Block is exactly equal to that of 5 ETH per block at $190.

If ongoing demand is ever reduced, or increased, then the price must likewise decrease or grow until the Daily Expenses equal that of Daily Demand.

Next, you must set a minimum required value for annual expenses for Hash Security. Budgets less than $20 Million have been attacked, $100 Million (or less) covers 999 block chains, $106 Million was the value for Ethereum 2016, $200 Million is that for Dash, and $230 Million is that value set by LiteCoin.

Thus, we can conclude that the minimum required value is between $20 Million, or over $250 Million to secure the 'safest block' chain. There is one alternative figure, which was calculated in this way:

What do you predict Ethereum will be worth in 2025? $500

Multiply that by 94,000,000 and 4%. That is the project cost of $2,100,000 Billion computers, today (hint Buy Computers! :)

As one could imagine, such a prediction would be grossly inaccurate. Would you rather rely upon 2009 or 2017 figures, when estimating the cost of Hash Security, in 2017? Regardless.

Let's play it safe and say the Minimum Desirable level for Hash Security is $500 Million (double that of LiteCoin), which is to say every block chain aside Bitcoin is unsafe, all the time, always have been, and so was Ethereum up until March, 2017.

Now, take this number and divide it by the total Demand. Which in our previous scenario was $5,472,000 daily or $1,997,280,000 annually. $500 Million / $1,997 Million = 25%.

This is the correct allocation of Demand Required to purchase the Minimum Desirable level of Hash Security. If more than 100% of Demand is Required, then your block chain is unsafe and you must abandon your product immediately, or create substantial new demand for your unsafe products, with the hopes of achieving safety and without any possibility for growth, ever, without additional increases in demand. This could be known as a "Bail Out".

Note : Regarding 51% Attack situations, prior investors can always temporarily readjust the % of inflation during a hard fork, to "Bail Out" a weakened block chain.

However, in all other situations, the Minimum Desirable level for Hash Security is less than 100% of Current Demand. In the above scenario, it was 25%.

Thus we can, and responsibly should, adjust the expense to meet the desire. This could either be obtained through Selling stored Ethereum until the price of $950 reduces to $190, or through reducing the rate of inflation to 25% of current value.

Today that value is 11.3% , times 25% = 2.8%. This would equate to $500 Million of Expenses at $190, or 2.8% x 25% = 0.7% at $950.

Thus, so long as demand remand constant, either $1,997 Million - $500 Million = $1,497 Million of Veteran funds must get released, or the price must go up. This matters not if the current price is $950 or $190. So long as demand exceeds costs, price must rise.

Historically, when Bitcoin has cut its expenses sharply, the price has doubled, or tripled, within 6 months. Which is to suggest a 6 month lag, within relatively inattentive markets with largely uninformed buyers.

Keeping within the Example, to require a Bail Out, Investor Demand would need to fall by over 75%, following a 75% reduction in expenses, as a percent of Demand. Which in this case would be a reduction of the Block Reward from 5 Eth to 1.25 ETH, so long as demand fell by less than 75%, the Minimum Desirable level for Hash Security would be maintained, while the Price would forcibly move up after Veteran funds become exhausted.

Assuming no change in demand, as it has little to no impact on demand, and a reduction of expenses and increased projected worth could only stimulate demand, realistically, however... assuming no change in demand $1.5 Billion annually must be released by Veterans to prevent a price escalation, increasing expense, until equilibrium, which would be around $760 in the prior scenario.

However, in between $190 and $760, it would once again approach a value in which the % of inflation could get halved again, which is logically $380.

Thus, we have a Demand in excess of Minimum Desired Hash Security Expenses, at a rate of 4 to 1. Without adjustment, Expenses will necessarily increase until a 1 to 1 ratio presents itself. Knowing this, we desire to reduce the % inflation spent on Hash Security between the Spot Prices of $190 and $760.

If we follow the standard of 'halves' , then it is most desirous to cut the % inflation in half at $380, exactly.

With Bitcoin it took approximately 6 Months for the Market to adjust by more than doubling the value of the Coin for each 50%, or similar, reduction.

If Ethereum reduced the rate of Issuance from 5 ETH to 1 ETH, I believe the markets would adjust amply in less than 5 months, or say 20% Monthly. Thus, after 3 months, the value could get once again reduced in half, while maintain the same Minimum Desired Hash Security Expenses.

For any miners which sell less than 100% of ETH daily, their profits actually increase, as they are able to sell less ETH, while awaiting for a proper market readjustment, and sell more while the expense is over valued, which naturally occurs between times of adjustment.

Given the expectation that reducing the rate of Inflation from 11.3% to 2.25% would naturally challenge Bitcoin in both cost Structure, and Market Cap, as well as Gold and US Dollars, I would recommend making a new 50% inflation reduction, assuming 1 ETH August 1st, 50% reduction November 1st, 50% reduction February 1st, and 50% reduction July 1st.

At this point you'd achieve a rate of inflation of 0.3%, and an significantly escalated price. Assuming demand reduces to that of half the current demand, then cutting the rate inflation in half every 6 months thereafter would seem reasonable, to allow for full market appreciation between 50% reductions.

Obviously one could use a lower % monthly, like 15%, however that creates less forced market volatility. Forced Market Volatility prevents someone from acquiring excessive ETH at a low price, and holding for years at highly profitable rates. With a consistently reduced monthly expense, one could create a time frame in which they could escalate the price, and temporarily corner the market (perhaps).

Alternatively, one could leave the rate of Inflation at 0.3% forever, which would essentially force a competing coin, or Casper, to enter the market, once the rate of Hash Security Expense exceeded the acceptable value by some $ figure, which we can assess to be around $2 Billion of annual tolerable waste, or perhaps $10 Billion to support something of such magnificence as 0.3% inflation.

However, with any block chain, they essentially lose their Investment Grade status once the rate inflation goes unchanged for longer than 6 months, after securing some consistent level of minimal demand. Regardless of the amount, if the Market Reacts to the change faster than Management, then Management becomes slacking, and the price falls and fluctuates in value, without any predictable future rise, until the next adjustment.

If Demand is in excess of Expenses by 20%, then one might reduce bonus expenses by 20%, and then 10% every 3 months thereafter or 20% every 6 months, to counter any attempt from a single actor to sell massive amounts of Coin, driving the Price to levels of temporary insecurity. The larger, and less frequent the reductions, the more difficult this becomes.

I personally recommend reductions no less frequently than once every 6 months, of 50%, for Ethereum, assuming demand is half that of today, 1 year from now.

**Comment by int03h** [comment]
How about we do some real math, that comprehends the situation right now? 
![diff](https://user-images.githubusercontent.com/5482481/28697161-04c3fa74-7308-11e7-9acd-99379fa88587.png)

A RX480 overclocked up the wazzoo and pretty reasonable power calcs : 
![inputs](https://user-images.githubusercontent.com/5482481/28697170-1caa86d0-7308-11e7-9f2a-ed30c4d00239.png)

This is all ABSOLUTE BEST CASE, GPU only, no infrastructure at all included, 0.12c is slightly adjusted to include cooling: 
![2017-07-27 4](https://user-images.githubusercontent.com/5482481/28696843-2b2eaf8a-7306-11e7-909e-e6c61e00cbd1.png)

Payouts roughly as follows - 8 months to recover $400 
![2017-07-27 4](https://user-images.githubusercontent.com/5482481/28697113-b099ab92-7307-11e7-9287-c25d6e8e9652.png)

With block reward dropped to 4ETH at current diff that 12 months 
![4eth](https://user-images.githubusercontent.com/5482481/28697278-a91619b8-7308-11e7-935f-4af723205a2b.png)

Even before touching the rewards, and 0% increase in diff, this picture really sucks. 

There are lots of new guys that parachuted in here trying to make a quick buck, they are going to be PISSED when they do the math. If the rewards are "adjusted" for any reason, even if it's a supremely good one, I believe it's going to reflect really badly on the project. 
  
tx ethscan.io  and coinwars.com.

**Comment by JoseQuavo** [comment]
https://qz.com/1039809/amd-shares-are-soaring-ethereum-miners-are-renting-boeing-747s-to-ship-graphics-cards-to-mines/

With respect to the above commenter it's clear when you see stories like the one published here that the issuance is absurdly profitable for miners and an extreme waste of power in the name of blockchain security.

**Comment by int03h** [comment]
With respect to @JoseQuavo , you are clearly not a miner, nor understands anything about mining. That piece you pasted is bordering on click-bait. Personally I would be rather ashamed of myself for pasting a puff piece like that into an EIP. I am not going to waste my time ripping it to shreds. If it's not obvious why it is absolute and total B$ then you really you should get out of crypto, at least when it comes to  mining and how "we" make money. (or usually don't - since most of the time we are way behind the curve due to the FACT that we HAVE TO take very long positions and we can't liquidate our capital when things get all groovy at $350). Running into brick walls (the diff) like this one, SUCKS.  Those dudes that rented that boeing are sweating bullets the size of Saturn V rockets right now, I guarantee it! I would bet a whole Boeing on it. The chapter 11 paperwork is on their desks. 

Programmatically attempting to interfere with the price by manipulating the payout is not going to go down well with those of us that didn't rent Boeings to try and make a quick buck out of what was really a bit of temporary insanity. Mining Ethereum is my passion. I have patiently invested TONS of time, money, and effort into the network for more than 2 years. I won't get any hugs and kisses from anyone.  Nor will any of the any other miners.  Trust me when I tell you, they are not happy campers right now. 

I KNOW I would have made MUCH more if I had just taken a cash position on ETH rather than mining. I didn't.  How stupid am I ? Now I are going to be punished because everyone went mad for a bit? I DON'T GET IT!?  I know we hurt the people we love, but this is crazy. 
 
Satoshi's original founding principal was that market dynamics would balance out these kinds of things, it will, and almost already has. You just don't see it yet, not sure why, it's pretty clear already in the stuff I did above. Maybe you lack perspective? Let me help :  what is a MASSIVE $1.49/day income today was  ABOUT (roughly) $10/day 4-5 weeks ago (for a VERY brief period - maybe 2 weeks). A few people must have made some good money. I managed to recover some of my investment. I am happy, but not  nearly as happy as I would have been if I have just had the ETH in hand.  That's all fine. This EIP makes me feel like you want to steal my wallet after I have just been in a car accident. It's a shitty thing to do, no matter how much sense it seems to make to you all right now. 

I will bet you another Boeing that my $1.49/day payout per card will be less than half of that in a month's time. EIP or not. IF I am making more than 70c per day this time next month -either because the price tanks or/and the diff keeps skyrocketing, I will be massively surprised.

**Comment by kybarnet** [comment]
You don't want to think of it in terms of "Profitable", but in terms of Waste. Every expense has a function, which should remain, at a minimum, relative to others, or be otherwise justified.

Regarding Hash Mining, the relative expenses are $20 Million to $250 Million for any coin created after 2009. I don't think there are known instances of successful hash attacks within this range, or say over $50 Million, maybe.

All above that is seen by the public as waste, generally.

However, Ethereum has a more substantial block chain, thus one might suggest $500 Million. Or if you say Ethereum must subsidize the entire mining community alone, $1 Billion. But those are some ranges, with $250 Million being the most in the market for anything else made after 2009, with no known problems with values above $50 to $20 Million.

Ethereum has other expenses - Research, Code Audits, Marketing, Seminars, Press, Community, Offices, Management, etc.  - These bonuses pay for one expenses only, 51% Hash Attack Protection. If 1 deadbolt protects a door, 100 deadbolts might seem excessive if they were costing $3 Billion annually in maintenance.

The reality is that Demand will near instantly equalize to Miner Expense, until the values become so large that they are legitimately difficult for a single nation to manipulate. Which is to say, Miners end up getting the same fixed $ payout, under any system, with the same demand, after market adjustment. For Bitcoin this takes about 6 months.

In systems such as Ethereum, in which demand is expected to grow, miners must consume all demand. This is the only possibility, under a growing demand curve. Regardless of the % of inflation, Hash Miners must consume all demand, until equilibrium. This is mathematically required.

Thus the payouts to miners will ultimately significantly increase. This is not the objective, but it is required. It is currently $2 Billion, but would grow to $6 Billion as Annualized Demand would be expected to (more realistically), grow from $2 Billion to $6 Billion post Metropolis release, particularly if Ethereum was the least inflationary economic system in the history of the world.

But as you can see, the amount of fixed $ spent for Hash Security must Grow, regardless of desire, assuming demand grows as well. Making a less desirable product only reduces demand, and reduces the amount Ethereum spends on Hash Security.

However, new demand must perpetually be created to prevent inflationary value erosion.

A great way to conceive the problem is, if you have $2,000 and earn $200 a year, and are taxed at a rate of 10% of accumulated wealth annually, how long will it take you to reach $3,000?

It mathematically can not happen.

Expenses for block chains are decided in this way. However, that Tax on Accumulated Wealth has an intended purpose, which costs $20 Million to $250 Million.

From there, you can make predictions regarding the speed and ability for which a market can correct to the proper demand to expense allocation. I believe this to be approximately 6 months, based on historical data following 50% expenses reductions with Bitcoin and the doubling or tripling of price.

Which is to say the $ paid to Miners Expenses increased dramatically after each time Bitcoin reduced it's percent of inflation by 50%. Run the math yourself, for a year before, to a year after, total value of bonuses paid to miners. It essentially doubles each time Bitcoin cut it's rate of Inflation by 50%. That's how we know you aren't being a selfish miner, you are actually trying to lose money ;)

Regardless, the principle in the end is don't waste money. That's all this is attempting to achieve.

Each time you reduce the percent of inflation, the market must catch up to achieve similar payouts. This occurs after approximately 3 to 6 months with Bitcoin. I personally believe the block chain market place is significantly more educated than it was a year ago, and thus I believe 3 months to be sufficient for the intro stages for Ethereum.

If the price became excessive for utility usage, it could be split 1,000 to 1 or similar, to ensure a high price did not deter functionality. However, having a predictably higher price, or investment grade asset, would significantly boost functionality, or reduce the risk, as excess Ether add value, rather than lose it.

**Comment by MicahZoltu** [comment]
Perhaps I missed it in this discussion, but has anyone stopped in to remind everyone that the _sole_ purpose of miners is to secure the network from attack?  Its purpose isn't to maintain price stability or reach a particular target market price.  The cost to secure the network is a function of `cost_to_launch_51_percent_attack` and `amount_of_value_transferred_per_effective_finality_time`.  What you need to consider is that if there are no value transfers happening on the network then you need _no_ hashing power.  You only need hashing power if value transfers are occurring (note: this includes indirect value transfers such as an update to a contract's state that changes ownership).

Similarly, if the entire net-worth of ETH is changing hands daily, then you need a _lot_ of hash power to secure that (far more than we currently have) because that is the amount of value at risk.  Until we have finality, calculating finality time is a bit tricky.  People tend to use 10 blocks, but the number of confirmations you use for finality is a function of the total value at risk in the system (how much could an attacker steal with double spends) relative to the cost of launching such an attack.

What this all means is that if we want _effective_ finality to be less blocks, we need more hashing power.  If we are OK with _effective_ finality being longer then we need less hashing power.  I haven't run the numbers, but I would be curious to know what _effective_ finality is given current ETH:USD price, current hash rate, and current amount of value transferred per unit of time (this last is really hard to calculate).

**Comment by spelgubbe** [comment]
Market was in a bubble, and you want to change ETH issuance based on how profitable mining was during a bubble? I'm losing faith.

**Comment by gurnted** [comment]
So you want to blatantly manipulate the market in a shameless attempt to rush a price hike at the expense of those who keep the chain secure?
 
That sounds almost as scummy as putting it to a vote on a site that determines outcome based on quantity of ethereum holdings the voters have.

Not that such things are absurd for this project. I mean after POS it will basically be f*** truth, the guy with the most ETH to put up rules and writes the history books. but anyway....

Problem with this proposed greed play is that it looks bad, has potential for public uncertainty, will cause those supplying security to find more profitable chains, and fixes nothing that won't be resolved with planned changes. 

Whether miners are paying for faster delivery of hardware, or people write out the math based on market conditions is irrelevant. Those numbers go out the window when dumping is due to the greed of hackers and ICOs. Miners didn't cause ETH to lose half its market share in the past few weeks (after it failed to scale well at peak conditions) any more than they are dragging the price down by producing too much. Oh, and they sure didn't stop it from growing 4000% either.  

In other words: The bubble has swollen at record pace all on it's own. Put the air compressor down and step away before you break something.

**Comment by georgiosd** [comment]
@MicahZoltu that's great, but how do you plan to reconcile the "defined sole purpose" with the fact that the mining operations require real dollar to create and to run and are 24/7? Would you expect miners to just take the pain when, for whatever reason, their service is not required? 

I made a length post at https://github.com/ethereum/EIPs/issues/186 with some points on trying to bridge the two sides. Please do make a more comprehensive effort to understand the other side also.

@spelgubbe I'm pretty sure you're making a good point but it's not coming across the way you phrased it, to me at least. Can you elaborate?

**Comment by MicahZoltu** [comment]
Miners making money isn't my problem, or any ethereum user's problem, aside from rewarding them enough to achieve target security.  At the moment, I suspect miners are _massively_ overcompensated in that they are providing significantly more security than the system needs.  This excess security spending comes out of the pockets of all ETH holders as a tax and is effectively "wasted" on excesses hashing power.

As users/developers, it isn't our job to make miners happy.  If we reduce the rewards to a more sane level, many miners will stop mining, but that is kind of the point.

As an analogy, ETH users are like people living in a small town with no crime who are paying hundreds of millions of dollars for private security forces.  They could be just as safe spending 1/10 of that (numbers all made up here).  Yes, reducing pay of private security will cause those security people to find jobs elsewhere and to move, possibly taking a loss on the house they just bought, but that isn't a reason to continue senselessly throwing money at them.

**Comment by georgiosd** [comment]
You're still not answering the question though.

In this fictional small town of yours, are you going to hire and fire security staff depending on your needs? Every day, every week, every month?

**Comment by MicahZoltu** [comment]
@georgiosd The idea is to have incentives be high enough that in the generally stable state of hashing power the system can withstand shocks to its security needs.  For example, if for whatever reason a bunch of people are spending ETH on off-chain goods during some event then there is an increased need for security during that event.  Ideally, the available hash rate should be enough to securely handle that transiently high volume of transfers.

So to answer your question (I think), "No, the idea isn't to constantly tweak/tune the security parameters."  As to what exactly that function is, I can say it is fairly complicated and the inputs are as described above.  Note that miner satisfaction isn't part of that function though.  😄

**Comment by alex-miller-0** [comment]
Moving discussion to this EIP per @5chdn's request.

This is starting to feel very nebulous and emotional, so I'd like to see a number get finalized soon. The initial EIP (which, I'd like to remind everyone, was written in December 2016) proposed a hardcoded decay based on block numbers that are now deprecated. In the spirit of the original EIP, I will propose an updated decay curve:

Beginning on block `BLOCK_METROPOLIS`, the issuance **halves** every **2 million blocks**. The first halving takes place on `BLOCK_METROPOLIS`, the second on `BLOCK_METROPOLIS+2000000`, etc. This leaves us with the following reward:

    Day 0      2.5 ETH
    Day 348  1.25 ETH
    Day 694  0.625 ETH

 If Casper is on track, we should only see the first halving. If it is delayed significantly, we will see the second. Hopefully we will never see the third, but I believe it is important to encode for future-proofing purposes.

For those who have been discussing the numbers in this EIP, does this seem reasonable?

**Comment by lightuponlight** [comment]
I think a simple change to 3 ETH / block is the best plan. It's much
simpler to implement and it's the Schelling point at the Carbonvote.

**Comment by MicahZoltu** [comment]
@alex-miller-0 When halving block reward, one can (generally) expect hashing power to halve (not exactly due to market inefficiencies).  This means block times will up to double, how long does Ethereum take to stabilize difficulty around the new hashing power?

**Comment by alex-miller-0** [comment]
@MicahZoltu Good question - I would have to look into that. I'm frankly fine with 30 second block times, but probably most people aren't.

@lightuponlight That's fine. I disagree numerically, but am happy to compromise as long as **something** gets done. If we can close this issue with a readjustment to 3 ETH/block at `BLOCK_METROPOLIS_1`, I and (I suspect) much of the community will be happy.

**Comment by MicahZoltu** [comment]
I similarly don't want to hold up Metropolis with in-fighting over block rewards, though I think a reduction to 3ETH is a bit pointless.  I personally recommend halving the reward today, then halving again every year.  This puts pressure on the community to switch to Casper as the security model will continue to deteriorate with each passing year until either the system is compromised or Casper is released.  Should Casper completely fall through, then we can re-evaluate and hard fork.

A reduction to 3ETH feels like it is just placating the "reduce the block reward" crowd and I _personally_ haven't heard any compelling arguments for keeping block rewards high as we head towards Casper.

As I have stated elsewhere, I think that people forget that miners are a service provider, they are not the customer.  Mining is also a very competitive business with very low barrier to entry and near zero cost to switch providers, so there is no need to keep the current set of service providers (miners) happy.  We only need to pay them enough to get the target amount of hashing power to show up, and nothing more.

Block rewards are part of the crypto-economic game theory around security, and ice age / reward decreasing should (IMO) be a pressure that forces people to switch to Proof of Stake (the long stated goal) because the system will eventually not be secure otherwise.  With a block reward minimum, the system could remain stable/secure indefinitely without ever switching to Casper, which means making the switch is more likely to result in a contentious fork.

If miners don't like the idea of Proof of Stake, there are plenty of other crypto-currencies that offer proof of work mining and continue to do so (including ETC).

**Comment by cbice66** [comment]
Changing the block reward to an arbitrary value after the network has scaled to this size is an incredibly dangerous move with very low return. Users don't care what the block reward is, they just want their coins and transactions to be safe. You can't pit miners against users and expect things to just work themselves out. Bitcoin miners know what to expect as far as block reward, and this keeps the network secure.

**Comment by spelgubbe** [comment]
23 seconds block time already, are things really going as planned?

I would really like to know what that target amount of hashing power is. Knowing that is required to set the emission of ether to a reasonable amount, not a stupid carbonvote.

**Comment by Arachnid** [comment]
Consensus on recent All Core Devs calls has been for a reduction to 3 ether.

Progressively decreasing issuance on a schedule is a bad idea both because we don't expect PoW to be around for long enough for it to matter, and because there's [good reason to believe](http://randomwalker.info/publications/mining_CCS.pdf) that a blockchain where transaction rewards outweigh block rewards is likely to be unstable.

Given that the ice age forces period hard forks anyway, it makes far more sense to adjust rewards if needed when that happens, rather than try and devise a schedule that works indefinitely.

**Comment by MicahZoltu** [comment]
> Consensus on recent All Core Devs calls has been for a reduction to 3 ether.
@Arachnid Was there a reason for this number or was it just pulled out of the air (like the original 5ETH block reward number)?  From the discussion here (unless I missed it) it appears that the 3ETH number just kind of magically appeared and started getting thrown around.

> because there's good reason to believe that a blockchain where transaction rewards outweigh block rewards is likely to be unstable.
That is the point, to set the system up for failure unless Casper is accepted.  By setting it to 3ETH, you are setting up a stable system that can run indefinitely _without_ upgrades, even though upgrades are desirable.  If you are arguing that the ice age is enough to force an eventual upgrade, then that is a more compelling argument.

> rather than try and devise a schedule that works indefinitely
To reiterate again, I'm specifically suggesting a system that does _not_ work indefinitely.  The purpose is to have a system that eventually breaks down if upgrades don't happen.  Though, this _is_ an overlap with the ice age, so perhaps its not worth trying to have two solutions to the same problem.

**Comment by alex-miller-0** [comment]
> Given that the ice age forces period hard forks anyway, it makes far more sense to adjust rewards if needed when that happens

This effectively addresses my concern (albeit in a procedurally inefficient way), so all good from my perspective. Glad there's consensus from the Core Devs. 👍

**Comment by Danieljohnsz** [comment]
I know that you are all devs, and see this issue from one side of the spectrum, so if you don't mind, please allow me to express the flip side of this spectrum (**the "bloated" miners perspective**), in real dollars, so that you can take that information and see when it takes you in terms of where to expect network hashing power to drop off from the difficulty bomb.

Real world numbers as of 8/3/2017:

I'm going to use a 4 GPU rig of GTX 1060's as my example, as it hashes nicely at an even 100 mh/s. Extrapolate this out for larger operations.

Hashing: **100 mh/s**
Wattage: **400w System + 50w Fan**
Mid-of-the-road Electric Rate: **.13 kWh**
Frugal build cost: **$1600**

Let's assume the miner started 6/1/2017, here would be his ETH earnings (Current USD $220):

June - 2.33 ETH   +512.60 -42.12 = $475.16
July - 1.35 ETH     +297.00 -42.12 = $254.88
Aug - .585 ETH    +128.70 -42.12 = $86.58
Sept - .285 ETH    +62.70  -42.12 = $20.58
Oct - .138 ETH      +30.36 -42.12  = ($11.76)
Nov - .067 ETH     +14.74 -42.12  = ($27.38)
Total                                                $798.06

So **by October** you'll see about **1/3 to 1/2 of hashing power drop off**, because they will have no chance of recouping their ROI and will be losing money by continuing.

**By November only the individuals that live near hydro or nuclear plants that get .03 kWh power will remain** and Ethereum would be a stretch to still call a "decentralized network".

Keep in mind:
* Miner does not hit ROI
* Miner's time is valued at zero
* Does not include hotter climates where A/C is required (Easily add 25-50% Cost)

With all this being stated, I hope that you can see that miners are not rolling around in piles of cash.  

Please consider this calculation in your decision to reduce block rewards and continue with current difficulty increases due to the bomb. 

We all want to see Ethereum succeed. If PoS was to release in full by the end of October, then perhaps the numbers work, but if the possibility of a year and a half wait time that's been thrown around is valid, then the network just simply can't sustain. Especially with a decrease in block reward.

**Comment by AndreasThom** [comment]
Looking at the problem from a game-theoretic/sociological perspective it may matter a lot if the developers agree now on on a progressively decreasing issuance or just decrease the issuance once and wait for the next ice age to make further decisions. The current situation is easy politically and it is unclear how it will develop if the transition to PoS is getting closer. It might well be that it will play a very important role what the "established state-of-the-art" is in one year and who is perceived as changing it or forking away. What is perceived as "classic" and what is not has mattered (unfortunately) quite a bit in similar situations in the past. Hence, one should definitely think now about how miners can be discouraged to block the transition to PoS. Having an increasingly bad economic environment would be one way - the transition to PoS should be inevitable even though the timeframe should remain flexible within reasonable bounds.

**Comment by Arachnid** [comment]
> Was there a reason for this number or was it just pulled out of the air (like the original 5ETH block reward number)? From the discussion here (unless I missed it) it appears that the 3ETH number just kind of magically appeared and started getting thrown around.

It's roughly the issuance at the time the HF is planned.

> That is the point, to set the system up for failure unless Casper is accepted. By setting it to 3ETH, you are setting up a stable system that can run indefinitely without upgrades, even though upgrades are desirable. If you are arguing that the ice age is enough to force an eventual upgrade, then that is a more compelling argument.

The ice age exists explicitly for this purpose. There's no reason to add a second mechanism that does the same thing.

@Danieljohnsz Reducing issuance will coincide with postponing the ice age, so will result in a restoration of difficulty to its original schedule.

**Comment by kybarnet** [comment]
@AndreasThom You make good points. I agree that Dollars are a suitable way to quantify expenses, historically and as future objectives.

Here is a clip of the core dev meeting on the subject, if curious. Enjoy!

https://www.youtube.com/watch?v=hRQg_lHEKl4&feature=youtu.be&t=41m51s

**Comment by M41** [comment]
The world of blockchain now enjoys a large degree of resiliency and miners have a lot of options.  Some miners will move on to other chains due to lack of sufficient ROI.  Difficulty decreases, remaining miners will enjoy a higher ROI and are happy to stay and continue mining.  We have seen it in the past, self-adjustment and habituating to new set of conditions.   That's what forks did.  They all worked out at the end to everyone's satisfaction or after coming into terms with it after a period of adjustment.

**Comment by larspensjo** [comment]
> It's roughly the issuance at the time the HF is planned.

I think this is the best solution. That way, nobody can be accused of
reducing the issuance to increase the price. As long as the slope of the
ice age difficulty is low enough, it also gives the miners a chance to
predict future issuance.

fre 4 aug. 2017 kl 17:26 skrev M41 <notifications@github.com>:

**Comment by Danieljohnsz** [comment]
@M41 That is ideal, but the difficulty isn't decreasing based on miners, it is increasing on a set schedule due to the difficulty bomb already set in place, to my understanding it won't fluctuate based on the current hashrate of the network, it will just continue to go up until we hit the ice age. Is this not the case?

**Comment by kybarnet** [comment]
Misplaced conversation from 669 moved to 186 per @5chdn request -

@Arachnid  - Wrote  -

> The bomb is not being 'frozen', just delayed. Any attempt to determine miner profitability needs to factor in second-order effects; if some miners move to other coins because Ether is no longer profitable, the difficulty will go down and mining profitability will go up, until it reaches an equilibrium.

@kybarnet - Replied -

You make good points Nick, it is unreasonable for Ethereum to insure unlimited number of miners are profitable. At one time, I heard the goal of supporting up to 10,000 Miners, or nodes, but that seems out the window, yes? Not sure our current number of nodes, but I think I've heard up to 35,000.

Likewise, when determining the Dollars of payout, the Price of Ethereum matters. 3 ETH at $220 is Equal to 2 ETH at $330, or 5 ETH at $132 or 1 ETH at $660. The total dollar of payout is a function of ETH x Price. Thus, if the objective is to secure a fixed or approximate dollar amount, it is worthwhile to consider market factors.

However, I've already done the math, and know that this argument is mute. Miners, Holders, Programmers, Users, all benefit from increased efficiency, and the more immediate and sudden, the better. No matter how large the increase in efficiency becomes, be it 3 or 2 or 1, miners will make astronomically more money than they did at 5 ETH, even at the $400 price. The only discussion currently is miners arguing to pay themselves less, but unknowingly.

I see. I have found the unspoken Math.
Ethereum is running 24,000 Nodes Currently at $2.2 Billion.

Factoring that Down to 10,000 Nodes equates to roughly $1 Billion.

Thus, the justification for the unspoken objective of securing $1 Billion in payouts. Good to know :)

If you were to pretend 5 ETH Equated to $2.2 Billion and represented a stable price, and reward was reduced to 3 ETH at $1 Billion, then a $1.2 Billion buy order would be forced upon the market, raising the miner bonuses until they were once again $2.2 Billion, long term. This adjustment takes about 2 months.

@int03h  - Replied -

@kybarnet nodes are not miners, nor are all miners nodes. Ethermine on its own 59782 active miners.
Miner bonuses don't rise. We get a flat fee of exactly 5ETH per block, every block, whether there is one miner or 2 million. So who exactly has this $1.2B that you are so obsessed with exactly ? 5 ETH x approx 4,040 a day @ $300/ETH = $6M a day x 30 = $182M a month.

@kybarnet - Replied -

"Flat rate of 5 ETH" . Holy Jesus man. 5 ETH at $20 = $100 , 5 ETH at $200 = $1,000.

For those that are observing the discussion from the outside, the Mining Union has brigaded the Ethereum Team so intently, it is now customary and acceptable to suggest there is no dollar value to Ethereum. To the outside world, it's widely accepted to be the Market Price, or about $280 currently. However, in programmer and miner discussions, they will suggest there is NO dollar value, and claim that 5 Eth at $10 is equal to 5 Eth at $400. The absurdity of such logic baffles some people, and they find it unbelievable that the anyone could actually believe such a statement, or even condone such discussion, regarding finances and Dollars of expense.

> To be clear, it is acceptable within the Ethereum Discussion to claim 20,000 ETH payments at $1 ($20,000) is exactly equivalent to payments at a price of $400 ($8,000,000). The claim is that these two numbers are equal, and purchase equivalent amount of goods within the real world, such as mining equipment (however this is blatantly, obviously, false).

@int03h I would be happy to continue discussing mining rewards with you for 5,000 ETH. You have a significant misunderstanding regarding the concepts of mining, and are hurting miners and Ethereum. If you value the importance of mining, I request you send me 5,000 ETH so that your false notions can be corrected, which is equivalent to about 4 hours of mining reward at 5 ETH. I hope you value mining discussions as much as I do.

2 Million blocks are created annually, so 3 ETH = 6,000,000 Eth issued to miners bonuses, per year.

At $20 per ETH, that's $120 Million annually, at $400 per ETH that's $2.4 Billion annually. A miner will say these numbers are the same.

**Comment by cbice66** [comment]
I think the math in these comments is very interesting. The assumption is that 1 block mined = 5 Ether issued, or 4 or 3 or 2 or 1, depending on the position being argued. But what about uncle rewards? These count towards the total circulating supply of Ether. When calculating Ether issuance and future supply, take into account the proportional uncle rewards for each block to make your position more transparent.

**Comment by alex-miller-0** [comment]
@cbice66 Good question. An uncle reward has been proposed here https://github.com/ethereum/EIPs/pull/669#issuecomment-315380512. I assume it will be included as part of EIP186.

**Comment by 5chdn** [comment]
If 649 replaces 186, then uncle reward will be updated, yes.

**Comment by lightuponlight** [comment]
A proportional reduction in uncle rewards is included in EIP-186.

**Comment by yuhong** [comment]
Thinking about it, GPU mining is so important I am surprised that AMD/NVIDIA senior executives aren't talking with coin developers. I prefer they do the work in public and use a SEC filing if needed to disclose to solve any Reg FD issues.

**Comment by nicksavers** [comment]
@lightuponlight This EIP seems to have been superseded and implemented by #649. Does this issue still need to remain open? If not could you close it please?

**Comment by Arachnid** [comment]
This pull request is referenced by #649, which has already been merged. As such, it needs to either be finalised and merged, or the dependency in the existing EIP needs to be removed.

**Comment by Arachnid** [comment]
I've removed the reference from 649, since this was never merged as an EIP.
